project:
  render:
    - tutorial.qmd
title: 'Solutions document: Causal Analytics & Improving User Sign Up Experiences'
format:
  html:
    output-file: "tutorial-10-solutions"
    output-ext:  "html"
