project:
  render:
    - tutorial.qmd
title: 'Teaching Guide: Causal Analytics & Improving User Sign Up Experiences'
format:
  html:
    output-file: "tutorial-10-teaching-guide"
    output-ext:  "html"
