## The Business Challenge

A fast-growing **fintech company** has just completed an A/B test to evaluate a new sign-up process that existing users must complete before accessing a new **feature release** in their account dashboard.
The goal of the experiment was to introduce this new process without creating excessive friction or drop-off during sign-up.

The company rolled out a **Test** variation of the sign-up flow, updating the layout and copy of key steps, while a **Control** group kept the original version.
You've received detailed event-level data showing when each user started, moved through the funnel, and confirmed.
The product team wants to know not only whether the Test increased completions, but *why* — and whether it created any new friction for users.

### Your Task

1. **Quantify the effect** of the new variation on completion rates.  
2. **Interpret the magnitude** of the improvement — is it large, small, or somewhere in between? 
3. **Explore additional metrics** to understand user behaviour inside the sign up process.  
4. **Prepare an executive summary** explaining whether the new sin should be rolled out to all customers.

### Loading R Packages

Here's the R packages we will need to complete the exercises: 

```{r}
#| message: false
#| warning: false
library(tidyverse)   # data wrangling
library(lubridate)   # dates and times
library(janitor)     # cleaning up and duplicate checks
library(vtable)      # balance table
```

The data comes in multiple files that we will load as we need them.
